import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, "../.."))
FILES_DIR = os.path.join(PROJECT_DIR, "files")
OUTPUT_HEADER = os.path.join(SCRIPT_DIR, "mrp-installer.h")

def list_files(dirpath):
    result = []
    for root, dirs, files in os.walk(dirpath):
        for f in sorted(files):
            full = os.path.join(root, f)
            rel = os.path.relpath(full, dirpath)
            result.append(rel)
    return result

def main():
    embed_files = list_files(FILES_DIR)
    print("=== mrplib Embedded File Generator ===")
    print(f"Scanning: {FILES_DIR}")
    files_data = []
    total_size = 0
    for relpath in embed_files:
        abspath = os.path.join(FILES_DIR, relpath)
        with open(abspath, "rb") as f:
            data = f.read()
        files_data.append(data)
        total_size += len(data)
        print(f"  [{len(data):10d} bytes] {relpath}")
    count = len(files_data)
    header_lines = []
    header_lines.append("/* Auto-generated by embed.py - do not edit */")
    header_lines.append("#ifndef MRPLIB_INSTALLER_EMBED_H")
    header_lines.append("#define MRPLIB_INSTALLER_EMBED_H")
    header_lines.append("")
    header_lines.append("#ifdef __cplusplus")
    header_lines.append('extern "C" {')
    header_lines.append("#endif")
    header_lines.append("")
    header_lines.append("#include <stddef.h>")
    header_lines.append("#include <string.h>")
    header_lines.append("")
    for i, data in enumerate(files_data):
        varname = f"embed_file_{i}"
        hexbytes = ", ".join(f"0x{b:02x}" for b in data)
        header_lines.append(f"static unsigned char {varname}[{len(data)}] = {{{hexbytes}}};")
    header_lines.append("")
    header_lines.append(f"static const char *embed_filenames[{count}] = {{")
    for relpath in embed_files:
        header_lines.append(f'    "{relpath}",')
    header_lines.append("};")
    header_lines.append("")
    header_lines.append(f"const unsigned char *embed_offsets[{count}] = {{")
    for i in range(count):
        header_lines.append(f"    embed_file_{i},")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append(f"unsigned int embed_lengths[{count}] = {{")
    for i, data in enumerate(files_data):
        header_lines.append(f"    {len(data)},")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append("static void init_embedded_files(void) {}")
    header_lines.append("")
    header_lines.append("#ifdef __cplusplus")
    header_lines.append("}")
    header_lines.append("#endif")
    header_lines.append("#endif")
    with open(OUTPUT_HEADER, "w") as f:
        f.write("\n".join(header_lines) + "\n")
    print(f"\nGenerated: {OUTPUT_HEADER}")
    print(f"  Files:  {count}")
    print(f"  Total:  {total_size} bytes")

if __name__ == "__main__":
    main()
